artifacts:
  root: "/mnt/nas/mtgnn"    # 네트워크 드라이브 루트
  project: "Bayesian"       # 하위 프로젝트 폴더
  models_dir: "models"      # 모델 저장 폴더
  plots_dir: "plots"        # 그림 저장 폴더(필요시)
  meta_dir: "meta"          # hp.txt 등 메타 저장 폴더(필요시)

saving:
  save_best_only: true
  best_filename: "best.safetensors"  # 항상 이 파일로 덮어쓰기
  best_hparams_filename: "best_hp.json"

logging:
  table: "training_logs"    # Postgres 테이블명
  experiment: "mtgnn_exp1"  # 실험명 태깅용(필요시)

solution_columns:
  - Solution_BLOCKCHAIN_Papers
  - Solution_ACCESS_CONTROL_Papers
  - Solution_ENCRYPTION_Papers
  - Solution_SUPPLY_CHAIN_RISK_MANAGEMENT_Papers
  - Solution_IDENTITY_MANAGEMENT_Papers
  - Solution_ML/DL_Papers
  - Solution_ANOMALY_DETECTION_Papers
  - Solution_CRYPTOGRAPHY_Papers
  - Solution_PENETRATION_TESTING_Papers
  - Solution_IDS/IPS_Papers
  - Solution_STATIC_ANALYSIS_Papers
  - Solution_DYNAMIC_ANALYSIS_Papers
  - Solution_MULTI_FACTOR_AUTHENTICATION_Papers
  - Solution_LEAST_PRIVILEGE_Papers
  - Solution_SESSION_MANAGEMENT_Papers
  - Solution_CAPTCHA_Papers
  - Solution_BLACKLISTING_Papers
  - Solution_RATE_LIMITING_Papers
  - Solution_GRAPHICAL_MODEL_Papers
  - Solution_HONEYPOT_Papers
  - Solution_SOFTWARE_DEFINED_NETWORK_Papers
  - Solution_GAME_THEORY_Papers
  - Solution_TRAFFIC_SHAPING_Papers
  - Solution_PACKET_FILTERING_Papers
  - Solution_BLACKHOLING_Papers
  - Solution_RANK_CORRELATION_Papers
  - Solution_STRONG_AUTHENTICATION_Papers
  - Solution_SSL/TLS_Papers
  - Solution_HTTPS_Papers
  - Solution_CONTINUOUS_AUTHENTICATION_Papers
  - Solution_IDENTITY_BASED_ENCRYPTION_Papers
  - Solution_DATA_SANITIZATION_Papers
  - Solution_OUTLIER_DETECTION_Papers
  - Solution_DATA_PROVENANCE_Papers
  - Solution_ADVERSARIAL_TRAINING_Papers
  - Solution_TRUSTWORTHY_AI_Papers
  - Solution_BAYESIAN_NETWORK_Papers
  - Solution_BEHAVIOR_BASED_DETECTION_Papers
  - Solution_FORMAL_VERIFICATION_Papers
  - Solution_SPLIT_MANUFACTURING_Papers
  - Solution_VULNERABILITY_MANAGEMENT_Papers
  - Solution_FILE_INTEGRITY_MONITORING_Papers
  - Solution_VPN_Papers
  - Solution_PRIVACY_PRESERVING_Papers
  - Solution_SECURE_BOOT_Papers
  - Solution_MERKLE_SIGNATURE_Papers
  - Solution_LIVENESS_DETECTION_Papers
  - Solution_3D_FACE_RECONSTRUCTION_Papers
  - Solution_BIOMETRICS_Papers
  - Solution_DIGITAL_WATERMARK_Papers
  - Solution_APPLICATION_WHITELISTING_Papers
  - Solution_DATA_BACKUPS_Papers
  - Solution_HIDDEN_MARKOV_MODEL_Papers
  - Solution_PATCH_MANAGEMENT_Papers
  - Solution_DATA_AUGMENTATION_Papers
  - Solution_DIMENSIONALITY_REDUCTION_Papers
  - Solution_DEFENSIVE_DISTILLATION_Papers
  - Solution_RRAM_Papers
  - Solution_SPATIAL_SMOOTHING_Papers
  - Solution_NOISE_INJECTION_Papers
  - Solution_TAINT_ANALYSIS_Papers
  - Solution_NETWORK_SEGMENTATION_Papers
  - Solution_USER_BEHAVIOR_ANALYTICS_Papers
  - Solution_DECEPTION_TECHNOLOGY_Papers
  - Solution_RISK_ASSESSMENT_Papers
  - Solution_DYNAMIC_RESOURCE_MANAGEMENT_Papers
  - Solution_SANDBOXING_Papers
  - Solution_DARKNET_MONITORING_Papers
  - Solution_VIRTUAL_KEYBOARDS_Papers
  - Solution_CODE_SIGNING_Papers
  - Solution_PUBLIC_KEY_INFRASTRUCTURE_Papers
  - Solution_MUTUAL_AUTHENTICATION_Papers
  - Solution_ONE_TIME_PASSWORD_Papers
  - Solution_DYNAMIC_BINARY_INSTRUMENTATION_Papers
  - Solution_PASSWORD_HASHING_Papers
  - Solution_DNSSEC_Papers
  - Solution_CERTIFICATE_PINNING_Papers
  - Solution_SECURE_SIMPLE_PAIRING_Papers
  - Solution_VULNERABILITY_ASSESSMENT_Papers
  - Solution_SIEM_Papers
  - Solution_STANDARDIZED_COMMUNICATION_Papers
  - Solution_CONTROL_FLOW_INTEGRITY_Papers
  - Solution_VULNERABILITY_SCANNER_Papers
  - Solution_PASSWORD_STRENGTH_METERS_Papers
  - Solution_PASSWORD_MANAGEMENT_Papers
  - Solution_PASSWORD_POLICY_Papers
  - Solution_GRAPHICAL_AUTHENTICATION_Papers
  - Solution_DATA_LOSS_PREVENTION_Papers
  - Solution_DATA_LEAKAGE_DETECTION/PREVENTION_Papers
  - Solution_ACTIVITY_MONITORING_Papers
  - Solution_MOVING_TARGET_DEFENSE_Papers
  - Solution_KEYSTROKE_DYNAMICS_Papers
  - Solution_ATTACK_TREE_Papers
  - Solution_DISTRIBUTED_LEDGERS_Papers
  - Solution_SOURCE_IDENTIFICATION_Papers
  - Solution_IMAGE_RECOGNITION_Papers
  - Solution_HYPERGAME_Papers
  - Solution_NLP/LLM_Papers

attack_columns:
  - DDoS-ALL
  - Phishing-ALL
  - Ransomware-ALL
  - Password Attack-ALL
  - Account Hijacking-ALL
  - Trojan-ALL
  - Vulnerability-ALL
  - Zero-day-ALL
  - Advanced persistent threat-ALL
  - Malware-ALL
  - Disinformation/Misinformation-ALL
  - Targeted Attack-ALL
  - Brute Force Attack-ALL
  - Backdoor-ALL
  - Botnet-ALL
  - Cryptojacking-ALL
  - Papers_DDoS
  - Papers_Phishing
  - Papers_Ransomware
  - Papers_Password_Attack
  - Papers_Account_Hijacking
  - Papers_Trojan
  - Papers_Vulnerability
  - Papers_Zero_day
  - Papers_Advanced_Persistent_Threat
  - Papers_Malware
  - Papers_Disinformation/Misinformation
  - Papers_Targeted_Attack
  - Papers_Brute_Force_Attack
  - Papers_Backdoor
  - Papers_Botnet
  - Papers_Cryptojacking
  - Papers_MITM
  - Papers_DNS_Spoofing
  - Papers_Dropper
  - Papers_Insider_Threat
  - Papers_Adversarial_Attack
  - Papers_Data_Poisoning
  - Papers_Deepfake
  - Papers_Supply_Chain
  - Papers_IoT_Device_Attack
  - Papers_Session_Hijacking
  - War_Conflict_All
  - Holidays
